name: puppeteer
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - glew=2.1.0
  - glib=2.68.4
  - pip=21.0
  - python=3.9.0
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - pip:
    - absl-py==2.0.0
    - "cython<3"
    - dm-control==1.0.8
    - ffmpeg==1.4
    - glfw==2.6.4
    - gym==0.21.0
    - hydra-core==1.3.2
    - hydra-submitit-launcher==1.2.0
    - imageio==2.33.1
    - imageio-ffmpeg==0.4.9
    - kornia==0.7.1
    - moviepy==1.0.3
    - mujoco==2.3.1
    - mujoco-py==2.1.2.14
    - numpy==1.23.5
    - omegaconf==2.3.0
    - pandas==2.1.4
    - setuptools==65.5.0
    - submitit==1.5.1
    - shimmy>=0.2.1
    - git+https://github.com/microsoft/MoCapAct.git
    - patchelf==0.17.2.1
    - protobuf==4.25.2
    - pillow==10.2.0
    - tensordict-nightly==2024.3.26
    - termcolor==2.4.0
    - torchrl-nightly==2024.3.26
    - tqdm==4.66.1
    - wandb==0.16.2
    - wheel==0.38.0
